language: node_js
node_js:
- '8'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=develop
  - secure: uHybVP4zMO1uVxWnV/Kj6OEyfQlJ1VYC8i2cqUu7kidSoaNq5Wg1OQ4fN/Wqbw7op3wbTB9my6GC2/nLf1nvI7FqLN9Bl//1tH3BoStiLNs3xYUC6azKUc85k9GeGyQZVHRA+YF7HaUoiPZrl0okPTv2/B+TMzqVAczXj/N9WIvhvfaRkh4goQNTnNmdhsP7MIYC7OSFmQ9toSsRWyUrallOZaZzGOac7t4UNhZUSJ+ewuay5VbBMXZc5TueKoWle5YOVjy9LdGKGCLHVKFOpUD8dM9bSh/07CuZAmEg2wh9QyBl8G/XSuvmcp6uWDaMuWdBUsX2+3wgYwE7bdmdK2x1v+kYhCKs5MEA/xnuqpi2c6UbLpT5RSCQJPSCgQwTvkxZ6opXX1Wpy6Z3U1j3nZoMns7onkKj4Mvwdz/qxP3I3jjMeczeaJcF1uX/b+0J2HvrfhPTCeiLQtkzE8zPdfS7HMCmWKJWa89+6q9AN4N5JnIbj+0e1jdvDYEZ6jLpU5ecu0HE0ghp4riQcTjzNedGNmU+IJMlDX7s+f9Z6Jo4oFw+B9QbpDcfmw5dPExVnb1/ot4zxPRz5l+Shj16ZYZu1yUXBMsufxmHXIvH+ElrsU5exPmOp94GlHRaM3rAYGDBuWLRN0frHjbN8f0BsEPFCaCm8/PnTthUrhDdyBE=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
  - bundle/cache
before_install:
- rvm install 2.3
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  cleanup: false
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
