language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=develop
  - secure: OxcX2NWC9p5Q7l7QL80OtfXV7J5Q8eXJ/AEU7iiWN/xz1giISrcAs2mTjl1BU+oclBGPt5TbP3qpBZCZlh7JoFisHBIMDS3GVjJEduNOrp64PjTwT0b4OS+eUaUMyGlR/XDP6/agqY08fI4rZw5hi/1aye4Iy2OiK0jPvnrG3JpdJIlROlVv60Sa5JKhkMwq8AhxNpP40FaNcYwT37J+Q85egV/GvwknkyXxC+lPCSU4N+YOvl3fhDY+PGIEXHoT+3gQBayS9DW+tAb6eQwAu5KOtNGOVTb1gjwDbTRQ0L90ctTK99tNvE8jeAxZ3kjXAIjL9RV2E5/FYS9tM1zi03JLvFUBhaKfpBL/fxk1o/cZPNe/0ItIW0NSJYxISW9XLXMi5BS6drIFkH47Izx9xoWi8DJ4GO2MvgGjNhw7EK2gjJ3RROuSfbNc2ZvTM3q21bku1kd24Y38c1oJ20W5TemJ9MiewivKusvCg7zLLiSqYA7BfIttZ5dYJ7XpkreUDqnmE4VgM6mAWRKBDle7NnjJsZRv/ZUfg4A7fEfRvQaCwaj7lxqayZW53Sqsun3CdH6ALJhATV2gbZjoyPlw5kG6wmaFGj9rs11siWY3h4rnGi04F6YOYV+nxsUuLn01q7RjSKImnyaGgOVB3XVA15swkQSX1y2ZpnRNmOdPMPo
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
  - bundle/cache
before_install:
- rvm install 2.1
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
