title: MoriartyNaps
email: moriartymaps@gmail.com
description: Daydreams of a sleepy carto fella.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moriartynaps.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  DylanMoriarty

# Build settings
source: app
safe: false
timezone: America/New_York

markdown: kramdown
theme: minima
gems:
  - jekyll-paginate-v2
exclude:
  - README.md
  - bundle
  - Gemfile
  - Gemfile.lock
# /vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb
# bundle/cache/ruby/2.3.0/gems/jekyll-3.4.3/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb

# Produces a cleaner folder structure when using categories
permalink: /:title/

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
############################################################
# Old jekyll-paginate pagination logic
#   Uncomment thew two entries below to demonstrate how this new gem
#   retains backwards compatibility with the old pagination logic 
#paginate: 3
#paginate_path: "/legacy/page:num/"