# Site settings
source: app
title: moriartynaps.com
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false 

syntax_highlighter: rouge

baseurl: ""

gems:
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 7
  permalink: '/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
