name: Deploy the damn thing
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: master
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
